name: CI Pipeline

# Evento que desencadena el workflow
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Puedes cambiar 'temurin' a otra distribución si lo necesitas.

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run tests with Maven
        run: mvn test